// <auto-generated />
namespace Codly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populateName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populateName));
        
        string IMigrationMetadata.Id
        {
            get { return "201912281643564_populateName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
